name: SSH Debug - Retrieve Secrets
on:
  workflow_dispatch:

permissions: {}

jobs:
  ssh-debug:
    runs-on: ubuntu-latest
    steps:
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@c0afd6f790e3a5564914980036ebf83216678101 # v3.23
        env:
          JETBRAINS_CERTIFICATE_CHAIN: ${{ secrets.JETBRAINS_CERTIFICATE_CHAIN }}
          JETBRAINS_PRIVATE_KEY: ${{ secrets.JETBRAINS_PRIVATE_KEY }}
        with:
          limit-access-to-actor: true
          timeout-minutes: 15
